### ISSUE TITLE
Entity Attributes 

### ISSUE THREAD

**Issue by jmendonza** [architectury/architectury#46] opened 2021-02-23 22:00 UTC
The architectury api is missing its own implementation of the fabric/forge equivalent, to assign attributes to entities:

Fabric:
> FabricDefaultAttributeRegistry.register(....)

Forge:
> ? GlobalEntityTypeAttributes.put(...)

**Comment by MaxNeedsSnacks** [comment] 2021-02-23 22:14
Duplicate of #31

**Closed as completed by MaxNeedsSnacks** 2021-02-23 22:14 UTC
