### ISSUE TITLE
[CRASH] Games Crashes when starting a new singleplayer world

### ISSUE THREAD

**Issue by szunakabeats** [architectury/architectury#187] opened 2022-01-30 14:12 UTC
1.16.5 / Architectury 1.28.48 / Fabric 0.12.12

[crash-2022-01-30_15.06.10-server.txt](https://github.com/architectury/architectury-api/files/7966051/crash-2022-01-30_15.06.10-server.txt)

**Comment by shedaniel** [comment] 2022-01-30 14:25
Duplicate of #174

**Closed as completed** 2022-01-30 14:25 UTC
Labels: duplicate, bug
