### ISSUE TITLE
1.26.42 Crashes

### ISSUE THREAD

**Issue by QueueAmI** [architectury/architectury#161] opened 2021-12-23 19:17 UTC
1.26.42 crashes with unexpected error, Exit Code: 0. I have removed all mods except for architectury and get the same error. I am running fabric-loader-0.11.7-1.16.5.

**Comment by QueueAmI** [comment] 2021-12-23 19:32
Update: I have tried multiple older version and get the same errors. I went further back and get an error stating that there are entry point errors.

**Comment by shedaniel** [comment] 2021-12-25 19:52
Duplicate of #151

**Closed as completed by shedaniel** 2021-12-25 19:52 UTC
Labels: invalid, duplicate
