### ISSUE TITLE
[1.18.1]  crashe on start (Differs from report below)

### ISSUE THREAD

**Issue by Terminal-Access** [architectury/architectury#171] opened 2021-12-30 17:25 UTC
## Installed mods:
Fabric loader 0.12.12
Fabric API 0.45.0
Architectury 3.3.6

Roughly Enough Items 7.1.357
Xaeros_Minimap 21.23.0_Fabric_1.18
XaerosWorldMap 1.19.0_Fabric_1.18

## Crash report:
[crash-2021-12-30_17.21.53-client.txt](https://pastebin.com/55BaM1wd)

**Comment by Terminal-Access** [comment] 2021-12-30 17:29
## Update: quick work around downgrade to Architectury v3.3.5

**Comment by Juuxel** [comment] 2021-12-30 17:33
Duplicate of #170.

**Closed as completed by Juuxel** 2021-12-30 17:33 UTC
Labels: duplicate

**Comment by Terminal-Access** [comment] 2021-12-30 17:41
Apologies I had copied the wrong crash report, here's the correct one
https://pastebin.com/55BaM1wd (I;ve updated the pastebin with the correct log)

has a different stack trace (more info prehaps you could use to track down this bug.)
