### ISSUE TITLE
Optifine Incompatibility 1.17

### ISSUE THREAD

**Issue by tetematete** [architectury/architectury#112] opened 2021-06-24 21:40 UTC
I'm running a small smp pack, and it seems like architectury and optifine/optifabric don't mix well atm. Any idea as to the cause?

**Comment by MaxNeedsSnacks** [comment] 2021-06-24 21:54
Duplicate of #105

**Comment by MaxNeedsSnacks** [comment] 2021-06-24 21:55
For reference, Optifabric released a patch recently, we're not sure if it works though since we have no part in that

**Closed as completed by MaxNeedsSnacks** 2021-06-24 21:54 UTC
Labels: invalid
