### ISSUE TITLE
minecraft keeps crashing!

### ISSUE THREAD

**Issue by brambora69123** [architectury/architectury#231] opened 2022-03-30 08:08 UTC
Heres my crash report:
https://pastebin.com/CzxjGU1j

**Comment by brambora69123** [comment] 2022-03-30 08:56
Apparently it sometimes loads but sometimes doesnt

**Comment by MaxNeedsSnacks** [comment] 2022-03-31 12:24
Duplicate of #135

**Closed as completed by MaxNeedsSnacks** 2022-03-31 12:24 UTC
Labels: duplicate
