### ISSUE TITLE
1.19.1 Crash when Applying Night Vision goggles from Pickle Tweaks

### ISSUE THREAD

**Issue by Zelioth** [architectury/architectury#318] opened 2022-08-12 06:37 UTC
Howdy,

I have created and been running my own custom 1.19.1 Forge server. I have found a bug in the most recent version where when some items are applied to the players head it crashed the textures and game. I will give some information as follows, Also I found the issue from applying Pickle Tweaks Night Vision Goggles. It's an instant crash. 

Minecraft Version 1.19.1
Architectury API Version 6.2.43
Forge Version 42.0.9

I will also post my crash report in two forms
https://crashy.net/SlEIj4jNcQvmHrJemqni

https://pastebin.com/TCBUMTr2

The mod pack I have created is called Friends United and it is listen on curse forge if you need to recreate the instance. Thank you and i really hope this helps

**Comment by triphora** [comment] 2022-08-12 10:33
@Lemonszz Is there any reason Biome Makeover keeps infecting stacktraces or does your mod just crash a lot?

**Comment by Lemonszz** [comment] 2022-08-12 11:09
Nope, it's generally pretty stable.

No clue about turning up in stacktraces, it's something I've been wondering for a while.  I assume I'm doing some janky classloading though a mixin or something.

**Comment by Zelioth** [comment] 2022-08-12 16:29
Hey, Thanks for looking at the issue but what would yall recommend. I know 1.19.1 isn't perfect by any means but what would be causing this issue? should I try a past version of Arch. or should I uninstall Biome MakeOver? And if i do will it mess up my worlds and server world that are already played on? Thank y'all

**Comment by MaxNeedsSnacks** [comment] 2022-10-20 13:01
Sorry for the long delay in reply, but:
1) These seem to be two separate crashes with completely separate causes.
2) We've (more or less predictably) since moved on to 1.19.2
3) That crash with the NV goggles is entirely unrelated to Architectury, the mod crashing here was JEED (Just Enough Enchantment Descriptions)
4) That other crash during loading was most likely caused by Biome Makeover (probably just another instance of #300 as well)

So I think I'll close this issue for now :P Thanks for reporting tho!

**Closed as not planned by MaxNeedsSnacks** 2022-10-20 13:01 UTC
Labels: invalid
