### ISSUE TITLE
Crash - Ticking memory connection

### ISSUE THREAD

**Issue by Jetpack-Cat** [architectury/architectury#342] opened 2022-09-20 16:12 UTC
Forge 1.16.5 Latest version of everything
architectury-1.32.66.jar

[crash-2022-09-20_09.10.22-server.txt](https://github.com/architectury/architectury-api/files/9609471/crash-2022-09-20_09.10.22-server.txt)

The game crashed

**Comment by plunginghornets** [comment] 2022-10-14 19:35
Similar crash in the same version, but considering we have very different mods, I don't know if the cause is the same. Let me know if I need to move this to a new issue.

https://paste.ee/p/umJtq

**Comment by MaxNeedsSnacks** [comment] 2022-10-20 12:56
Duplicate of #286

**Closed as not planned by MaxNeedsSnacks** 2022-10-20 12:56 UTC

**Comment by SiverDX** [comment] 2024-01-31 15:08
Meant to write this in the open issue
