### ISSUE TITLE
v1.8.124 Fails to start

### ISSUE THREAD

**Issue by Blobanium** [architectury/architectury#50] opened 2021-02-25 19:42 UTC
So whats happening here is that the mod is crashing on startup.

Log
[latest.log](https://github.com/architectury/architectury-api/files/6045371/latest.log)

if you need anything else tell me thanks

**Comment by shedaniel** [comment] 2021-02-25 19:45
Duplicate of #49

**Closed as completed by shedaniel** 2021-02-25 19:45 UTC
