### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by moisties** [architectury/architectury#67] opened 2021-03-29 20:57 UTC
Moving this mod out of the folder causes it to not crash.
[2021-03-29-6.log](https://github.com/architectury/architectury-api/files/6224487/2021-03-29-6.log)
[crash-2021-03-29_13.38.02-client.txt](https://github.com/architectury/architectury-api/files/6224489/crash-2021-03-29_13.38.02-client.txt)

**Comment by moisties** [comment] 2021-03-29 20:58
This is on the latest version, 1.10.139

**Comment by MaxNeedsSnacks** [comment] 2021-03-30 21:40
This seems to be an issue with ItemPhysicLite's js coremod, I'll look into what causes it to crash in the end but the fact that their coremod isn't applying correctly in the first logfile is a concerning sign.

**Comment by MaxNeedsSnacks** [comment] 2021-04-05 02:40
In the meantime, can you try to reproduce this without ItemPhysicLite installed?

**Comment by MaxNeedsSnacks** [comment] 2021-06-01 13:21
Gonna close this for now since this just seems to be an issue on ItemPhysicLite's end, feel free to reopen if anything new comes up!

**Closed as completed by MaxNeedsSnacks** 2021-06-01 13:21 UTC
Labels: bug, question
