### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by Aessar** [architectury/architectury#124] opened 2021-07-31 21:10 UTC
MultiMc fails to launch the game with "Architectury API (Fabric)" installed (using the newest version availabal for 1.16.5, log below.
Any help on whats going on here on how to fix "this"? Im not very knowledgeable on this topic. Since the issue only happens with Architectury installed I assume that its the cause.

[22:55:59] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=Knot/Fabric Env=CLIENT
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-networking-blockentity-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-rendering-data-attachment-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-renderer-indigo.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-events-interaction-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-loot-tables-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-renderer-registries-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-blockrenderlayer-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-renderer-api-v1.debughud.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-containers-v0.accurate.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-rendering-fluids-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config stepheightentityattribute.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-resource-loader-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-game-rule-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-object-builders-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-tag-extensions-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-rendering-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-transfer-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-item-groups-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-command-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-crash-report-info-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-entity-events-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-renderer-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-screen-handler-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-lifecycle-events-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-containers-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-structure-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-item-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-object-builder-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config mixins.terraform-boats.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-screen-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-dimensions-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-textures-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-registry-sync-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-models-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-biome-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-networking-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-particles-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config mixins.terraform-leaves.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-tool-attribute-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-content-registries-v0.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-api-lookup-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config trinkets.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config fabric-key-binding-api-v1.mixins.json does not specify "minVersion" property
[22:56:00] [main/ERROR] [mixin/]: Mixin config mixins.terraform-signs.json does not specify "minVersion" property
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.SecurityException: class "org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.initializeTransformers(KnotClassDelegate.java:77)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more

**Comment by Juuxel** [comment] 2021-08-01 07:06
> Caused by: java.lang.SecurityException: class "org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy"'s signer information does not match signer information of other classes in the same package

This error is really suspicious, as well as the fact that it's seemingly using upstream mixin instead of Fabric's. @shedaniel do you have any idea what's causing this?

**Comment by shedaniel** [comment] 2021-08-01 07:10
No idea, we might want @Aessar to export their MultiMC instance to us, quite interesting that it only crashes with architectury installed? Architectury couldn't be forcing upstream mixin possibly?

**Comment by Aessar** [comment] 2021-08-01 23:02
Do you want me to do that? Your gonna have to explain me how to tho.

**Comment by shedaniel** [comment] 2021-08-02 02:23
You can select an instance, right click, and click Export Instance, basically tick all folders, and send that exported zip somewhere like google drive. It would help a lot :p

**Comment by Aessar** [comment] 2021-08-02 13:36
https://drive.google.com/file/d/1Mf4vqYS4E6fxb9XUV9Mlga0iNFIENJ9I/view?usp=sharing  The file should be in this drive link

**Comment by LunaVid6231** [comment] 2022-01-30 16:02
It happens exactly the same to me, the game fails to launch

**Comment by RashbaNor** [comment] 2022-02-14 18:57
Well, unfortunately I have the exact same problem.

**Comment by Kitt3yL0v3r66** [comment] 2022-03-06 18:11
Just curious but is this the same Mixin error?
[Info: 2022-03-06 18:07:29.0708041: GameCallbacks.cpp(177)] Game/FabricLoader/Metadata (main) Warn Mod `soaringstructures2` (1.18 - 2.1) does not respect SemVer - comparison support is limited.
[Info: 2022-03-06 18:07:29.2936697: GameCallbacks.cpp(177)] Game/FabricLoader/Mixin (main) Info SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/kitt3/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[Info: 2022-03-06 18:07:29.3705382: GameCallbacks.cpp(177)] Game/FabricLoader/Mixin (main) Info Compatibility level set to JAVA_16
[Info: 2022-03-06 18:07:29.3787809: GameCallbacks.cpp(177)] Game/FabricLoader/Mixin (main) Info Compatibility level set to JAVA_17
[Info: 2022-03-06 18:07:29.5605004: GameCallbacks.cpp(177)] Game/Lithium (main) Info Loaded configuration file for Lithium: 102 options available, 0 override(s) found
[Info: 2022-03-06 18:07:29.6253076: GameCallbacks.cpp(177)] Game/Sodium (main) Info Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[Info: 2022-03-06 18:07:30.0228439: GameCallbacks.cpp(177)] Game/Effective (main) Info Sodium found. Applying compatibility mixin...
[Info: 2022-03-06 18:07:30.1154692: GameCallbacks.cpp(177)] Game/FabricLoader/Mixin (main) Warn Error loading class: net/minecraft/class_6861 (java.lang.ClassNotFoundException: net/minecraft/class_6861)
[Info: 2022-03-06 18:07:30.1162186: GameCallbacks.cpp(177)] Game/FabricLoader/Mixin (main) Warn @Mixin target net.minecraft.class_6861 was not found fabric-resource-loader-v0.mixins.json:LifecycledResourceManagerImplMixin
[Info: 2022-03-06 18:07:30.4444236: GameCallbacks.cpp(177)] Game/Sodium (main) Warn Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[Info: 2022-03-06 18:07:30.6891276: GameCallbacks.cpp(177)] Game/Sodium (main) Info Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[Info: 2022-03-06 18:07:30.8215419: GameCallbacks.cpp(177)] Game/FabricLoader (main) Error Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'com.mojang.bridge.game.GameVersion net.minecraft.class_3797.method_16672()'
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'com.mojang.bridge.game.GameVersion net.minecraft.class_3797.method_16672()'
	at fudge.notenoughcrashes.fabric.StacktraceDeobfuscator.<clinit>(StacktraceDeobfuscator.java:29)
	at net.minecraft.client.main.Main.handler$cli000$asSoonAsPossible(Main.java:517)
	at net.minecraft.client.main.Main.main(Main.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more

**Comment by Juuxel** [comment] 2022-03-06 22:08
@Kitt3yL0v3r66 No, this is a different issue that is unrelated to architectury (seems to be notenoughcrashes crashing when deobfuscating another crash, ironically enough)

**Comment by Kitt3yL0v3r66** [comment] 2022-03-07 03:58
That is actually kinda funny, I seem to be getting a crash even with it removed, really bugging me sense the mods I had were working fine a while ago

**Comment by MaxNeedsSnacks** [comment] 2022-03-19 04:29
This is unfortunately one of those *very difficult to reproduce* issues, so I'm just asking out of curiosity: @Aessar does this issue still happen to you when trying to launch packs with Architectury (either this original instance or some other pack using it that you've played more recently)? Since this issue attracts a fair bit of unrelated traffic, I'll probably have to close this either way, but I at least would like to know whether by some miracle, this issue fixed itself :p

**Comment by b0b1126** [comment] 2022-05-04 00:54
also crashing on start

Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to obtain root directory for mod 'roughlyenoughitems-default-plugin'!
    at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:148)
    at net.fabricmc.loader.impl.ModContainerImpl.getRootPaths(ModContainerImpl.java:100)
    at net.fabricmc.loader.api.ModContainer.findPath(ModContainer.java:62)
    at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:481)
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: Error accessing file:///C:/Users/dda11/AppData/Roaming/.minecraft/.fabric/processedMods/roughlyenoughitems-default-plugin-5.12.385-6a449b1be23b29f1.jar: java.util.zip.ZipError: zip END header not found
    at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:83)
    at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:59)
    at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPath(ModContainerImpl.java:156)
    at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:137)
    ... 6 more
Caused by: java.util.zip.ZipError: zip END header not found
    at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
    at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
    at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
    at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
    at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
    at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
    at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
    at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:78)
    ... 9 more

**Comment by MaxNeedsSnacks** [comment] 2022-05-22 19:55
Since the original issue has since been hijacked by a bunch of unrelated reports and we can't seem to reproduce this reliably, I'm gonna be closing this for now

**Closed as not planned by MaxNeedsSnacks** 2022-05-22 19:55 UTC
Labels: bug, question, priority: high
