### ISSUE TITLE
Seemingly random crash due to architectury.

### ISSUE THREAD

**Issue by Hasturspex** [architectury/architectury#234] opened 2022-04-04 15:44 UTC
I'm making my own small modpack, and after coming back after a few days away, I try to launch Minecraft, but architectury crashes for seemingly no reason. I distinctly remember restarting it without changing anything, and it worked. I was in the process of benchmarking performance with several different mods, and it was a coin toss whether architectury would crash or not.
I will provide a full crash log below.

crash-2022-04-04_17.25.57-fml

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 04/04/2022, 17:25
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.1-39.1.2-universal.jar%2394!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:169) ~[forge-1.18.1-39.1.2-universal.jar%2394!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:554) ~[client-1.18.1-20211210.034407-srg.jar%2390!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:569) ~[client-1.18.1-20211210.034407-srg.jar%2390!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:548) ~[client-1.18.1-20211210.034407-srg.jar%2390!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.18.1-20211210.034407-srg.jar%2390!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1254) ~[client-1.18.1-20211210.034407-srg.jar%2390!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1041) ~[client-1.18.1-20211210.034407-srg.jar%2390!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%2390!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2390!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.2.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.architectury.event.forge.EventHandlerImpl.lambda$registerClient$0(EventHandlerImpl.java:32) ~[architectury-3.7.37.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
-- MOD architectury --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.1.2.jar%2392!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.1.2.jar%2391!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: architectury-3.7.37.jar
	Failure message: Architectury (architectury) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 3.7.37
	Mod Issue URL: https://github.com/shedaniel/architectury/issues
	Exception message: java.lang.IllegalStateException: Where is architectury?
Stacktrace:
	at dev.architectury.event.forge.EventHandlerImpl.lambda$registerClient$0(EventHandlerImpl.java:32) ~[architectury-3.7.37.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at dev.architectury.event.forge.EventHandlerImpl.registerClient(EventHandlerImpl.java:32) ~[architectury-3.7.37.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.EventHandler.registerClient(EventHandler.java) ~[architectury-3.7.37.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.EventHandler.init(EventHandler.java:38) ~[architectury-3.7.37.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.forge.ArchitecturyForge.<init>(ArchitecturyForge.java:33) ~[architectury-3.7.37.jar%2355!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.1.2.jar%2392!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.1.2.jar%2391!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 592488736 bytes (565 MiB) / 4294967296 bytes (4096 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1123
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33637.94
	Virtual memory used (MB): 13175.36
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 61.30
	JVM Flags: 12 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -Xmx8G -Xms4G -Xmn6G -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ParallelGCThreads=16
	OptiFine Version: OptiFine_1.18.1_HD_U_H6
	OptiFine Build: 20220324-210209
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 511.23
	OpenGlRenderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		inventorysorter-1.18-19.0.0.jar                   |Simple Inventory Sorter       |inventorysorter               |19.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		theoneprobe-1.18-5.0.4.jar                        |The One Probe                 |theoneprobe                   |1.18-5.0.4          |COMMON_SET|Manifest: NOSIGNATURE
		netherportalfix-forge-1.18-9.0.0.jar              |NetherPortalFix               |netherportalfix               |9.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.1-9.4.1.168.jar                          |Just Enough Items             |jei                           |9.4.1.168           |COMMON_SET|Manifest: NOSIGNATURE
		AttributeFix-Forge-1.18.1-13.0.5.jar              |AttributeFix                  |attributefix                  |13.0.5              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		modnametooltip-1.18.1-1.18.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.18.0              |COMMON_SET|Manifest: NOSIGNATURE
		kleeslabs-forge-1.18.1-11.0.1.jar                 |KleeSlabs                     |kleeslabs                     |11.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.1.jar                     |Flywheel                      |flywheel                      |1.18-0.6.1.63       |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.18.1-65.jar                           |Patchouli                     |patchouli                     |1.18.1-65           |COMMON_SET|Manifest: NOSIGNATURE
		FastSuite-1.18.1-3.0.0.jar                        |Fast Suite                    |fastsuite                     |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.0+5.jar                   |Clumps                        |clumps                        |8.0.0+5             |COMMON_SET|Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.4-1.18+.jar        |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		FastWorkbench-1.18.1-6.0.1.jar                    |Fast Workbench                |fastbench                     |6.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.18.1-9.0+15.jar               |Controlling                   |controlling                   |9.0+15              |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.18.1-6.1.1.jar                          |Placebo                       |placebo                       |6.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughProfessions-1.18-1.2.2.jar              |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		entityculling-forge-mc1.18-1.5.0.jar              |EntityCulling                 |entityculling                 |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		lazydfu-1.0-1.18+.jar                             |LazyDFU                       |lazydfu                       |0.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		FastFurnace-1.18.1-6.0.2.jar                      |FastFurnace                   |fastfurnace                   |6.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		jeed-1.18.1-1.8.jar                               |Just Enough Effect Description|jeed                          |1.18.1-1.8          |COMMON_SET|Manifest: NOSIGNATURE
		architectury-3.7.37.jar                           |Architectury                  |architectury                  |3.7.37              |ERROR     |Manifest: NOSIGNATURE
		ftb-library-forge-1801.3.5-build.109.jar          |FTB Library                   |ftblibrary                    |1801.3.5-build.109  |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-4.1.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.1.2               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		AI-Improvements-1.18-0.4.0.jar                    |AI-Improvements               |aiimprovements                |0.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		balm-2.4.3+0.jar                                  |Balm                          |balm                          |2.4.3+0             |COMMON_SET|Manifest: NOSIGNATURE
		ToastControl-1.18.1-6.0.1.jar                     |Toast Control                 |toastcontrol                  |6.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		FpsReducer2-forge-1.18.2-2.0.jar                  |FPS Reducer                   |fpsreducer                    |1.18.2-2.0          |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.141.jar         |Just Enough Resources         |jeresources                   |0.13.1.141          |COMMON_SET|Manifest: NOSIGNATURE
		ftb-teams-forge-1801.2.5-build.48.jar             |FTB Teams                     |ftbteams                      |1801.2.5-build.48   |COMMON_SET|Manifest: NOSIGNATURE
		ftb-chunks-forge-1801.3.3-build.113.jar           |FTB Chunks                    |ftbchunks                     |1801.3.3-build.113  |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-6.2.57-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.57              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.1-39.1.2-universal.jar                 |Forge                         |forge                         |39.1.2              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.18-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-27.2.jar                            |FastLeafDecay                 |fastleafdecay                 |27.2                |COMMON_SET|Manifest: NOSIGNATURE
		Babel-3.0.1.jar                                   |Babel                         |babel                         |3.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		JEPB-1.1.0.jar                                    |Just Enough Piglin Bartering  |jepb                          |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		craftingtweaks-forge-1.18.1-14.0.1.jar            |CraftingTweaks                |craftingtweaks                |14.0.1              |COMMON_SET|Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: c767f1e3-9019-41c5-a34e-838a6e26e1ec
	FML: 39.1
	Forge: net.minecraftforge:39.1.2

**Comment by MaxNeedsSnacks** [comment] 2022-04-04 17:05
Duplicate of #135

**Closed as completed by MaxNeedsSnacks** 2022-04-04 17:05 UTC
