### ISSUE TITLE
Server cannot handle anyone joining.

### ISSUE THREAD

**Issue by sctjkc01** [architectury/architectury#134] opened 2021-09-06 00:13 UTC
I'm running ATM6 1.7.11 with a small handful of other mods on a dedicated server - 
[this is the modlist](https://github.com/architectury/architectury-api/files/7112565/modlist.txt).  We just now had to remove Chisels & Bits from that because it crashes in full when players login.

Whenever someone attempts to join the server, the server Event Bus reports `Exception caught during firing event: null`, points a finger at `class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V`, and forcibly disconnects the player stating a failure to handle the packet with a null pointer exception.

Full stacktrace of packet handle failure:
```
java.lang.NullPointerException: null
        at java.lang.invoke.DirectMethodHandle$Interface.checkReceiver(DirectMethodHandle.java:407) ~[?:1.8.0_292] {}
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_292] {}
        at me.shedaniel.architectury.event.EventFactory.invokeMethod(EventFactory.java:71) ~[architectury:?] {re:classloading}
        at me.shedaniel.architectury.event.EventFactory.access$000(EventFactory.java:42) ~[architectury:?] {re:classloading}
        at me.shedaniel.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:80) ~[architectury:?] {re:classloading}
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.sun.proxy.$Proxy121.join(Unknown Source) ~[?:?] {}
        at me.shedaniel.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:110) ~[architectury:?] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_929_EventHandlerImplCommon_event_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:common.PlayerListMixin,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:blue_skies.mixins.json:PlayerListMixin,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:kubejs-common.mixins.json:PlayerListMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}
```

In case you want full log files, here you go:
[latest.log](https://github.com/architectury/architectury-api/files/7112559/latest.log)
[debug.log](https://github.com/architectury/architectury-api/files/7112560/debug.log)

The first failure happens at line 30800 in the debug.log file, 2337 in latest.log.

**Comment by sctjkc01** [comment] 2021-09-06 00:16
For what it's worth, I don't think it's a full duplicate of #125 because of a slight difference in the stacktrace... and I'm unsure if everyone is blocked or only a select few because of a small sample size (private server with only 5-6 people).

**Comment by oliverrook** [comment] 2021-09-24 20:22
Got this but in single player world upon trying to join the world after it was created. First time when it was made worked fine.

**Comment by MaxNeedsSnacks** [comment] 2021-10-02 17:12
This *might* be a duplicate of #125 as you said before, but would it be possible for you to try and reproduce this with enhanced NPEs enabled (on Java 14+ with `-XX:+ShowCodeDetailsInExceptionMessages` in the launch options or just using J15+)?

I just can't make sense of this issue still, apart from it possibly being a downstream consumer (i.e. some mod using Architectury's event system) erroring rather than Arch itself

**Comment by MaxNeedsSnacks** [comment] 2022-03-19 04:25
Merging this into #125 (despite not being a full duplicate)

**Closed as completed by MaxNeedsSnacks** 2022-03-19 04:25 UTC
Labels: bug, priority: medium
