### ISSUE TITLE
【bug】game can not start at 1.18.1

### ISSUE THREAD

**Issue by blood789** [architectury/architectury#173] opened 2022-01-04 13:26 UTC
game can not start at 1.18.1......

This situation does not happen every time. Approximately every 10 times the game is started, it will happen once.
[latest.log](https://github.com/architectury/architectury-api/files/7807851/latest.log)
[debug.log](https://github.com/architectury/architectury-api/files/7807852/debug.log)
[crash-2022-01-04_21.20.27-fml.txt](https://github.com/architectury/architectury-api/files/7807854/crash-2022-01-04_21.20.27-fml.txt)

**Comment by blood789** [comment] 2022-01-04 13:28
THE game show that :
Architecture has failed to load correctly.
java.lang.reflect.invovationTargetException: null

**Comment by shedaniel** [comment] 2022-01-04 13:58
Duplicate of #135

**Closed as completed by shedaniel** 2022-01-04 13:58 UTC
Labels: duplicate, bug
