### ISSUE TITLE
[Neoforge 1.21] Crash on start up (21.0.75-beta)

### ISSUE THREAD

**Issue by unspunreality** [architectury/architectury#537] opened 2024-07-07 18:20 UTC
https://mclo.gs/h1FeCIG

Just as it says on the tin. Back at .61 was fine, did an update today to .75 and bazinga~ So I'll just assume stuff changed and crash.

**Comment by unspunreality** [comment] 2024-07-07 18:27
Just to add. The change happens at .67 for Neoforge. Im not smart enough to find out what changed but .66 loads fine, .67 is when crashes begin. I'm sure you can find out specifics but figured I'd do my due diligence and offer whatever help I could.

**Comment by ThexXTURBOXx** [comment] 2024-07-09 07:13
Seems to be related to some conflict or other badly coded mod since loading NeoForge and Architectury alone does not create any conflicts. Probably duplicate of #527

Edit: Also, there are like 5 mods that fail to load due to some errors. Does the game still not load when disabling duckling, chococraft, doggytalents, grimoireofgaia, and mekanism?

![grafik](https://github.com/architectury/architectury-api/assets/12763829/1ea0ac8e-6724-4dc4-a812-1907f1b3bcb0)

**Comment by Jab125** [comment] 2024-07-09 07:51
> https://mclo.gs/h1FeCIG
> 
> Just as it says on the tin. Back at .61 was fine, did an update today to .75 and bazinga~ So I'll just assume stuff changed and crash.

NeoForge is in it's breaking changes phase, so you'll often encounter issues with it until it stabilizes.

**Comment by unspunreality** [comment] 2024-07-09 12:58
> Seems to be related to some conflict or other badly coded mod since loading NeoForge and Architectury alone does not create any conflicts. Probably duplicate of #527
> 
> Edit: Also, there are like 5 mods that fail to load due to some errors. Does the game still not load when disabling duckling, chococraft, doggytalents, grimoireofgaia, and mekanism?
> 
> ![grafik](https://private-user-images.githubusercontent.com/12763829/346853678-1ea0ac8e-6724-4dc4-a812-1907f1b3bcb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzAwNjcsIm5iZiI6MTcyMDUyOTc2NywicGF0aCI6Ii8xMjc2MzgyOS8zNDY4NTM2NzgtMWVhMGFjOGUtNjcyNC00ZGM0LWE4MTItMTkwN2YxYjNiY2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEyNTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YWE0ZGIzNWU3ZjVlMTA1OWYzMWQ1Y2M5Y2EyOTBkNTFmZGM4NmJkMjkyN2EwMjRjNmJkYjUyY2JhM2UxYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kG52RJeSjmXTcc06SALyjGnzhOX8TJhb-uQv9jYLU_E)

Thanks for saying this. All honesty Ill admit my mistake. It was either animal feeding trough or dark enchanting. I didnt do my own proper due diligence to see if the mods that rely on arch were the culprit and a simple on and off earlier with various mods woulda found this out. Salute and I guess this can be closed then. Sorry all.

Edit: And the other mods were fine. But they all also updated recently so they could have fixed whatever was the proper underlying issue.

**Closed as completed** 2024-07-11 01:37 UTC
