### ISSUE TITLE
[curseforge] allow use of curseforge api with third party launchers

### ISSUE THREAD

**Issue by Merith-TK** [architectury/architectury#266] opened 2022-05-24 23:06 UTC
![image](https://user-images.githubusercontent.com/10422110/170145958-4c5e0751-1388-4dc6-9b04-4938007a735d.png)

legit, curseforge updated their api forcing this to be enabled if the mod is to be downloaded without the curseforge launcher or manually downloading it directly

**Comment by shedaniel** [comment] 2022-05-24 23:07
Duplicate of #262

**Closed as completed by shedaniel** 2022-05-24 23:07 UTC
Labels: duplicate
