### ISSUE TITLE
Crash: Mod Incompatibility

### ISSUE THREAD

**Issue by Atlantispy** [architectury/architectury#190] opened 2022-02-01 16:03 UTC
Hi, 

Have reported to them as well, but using the 7.2.9 version of world edit will cause Architectury to run incorrectly (both 3.4.9 which is the current build in Atlan SMP modpack, and the latest build), and crash.

**Comment by Atlantispy** [comment] 2022-02-01 16:03
[crash-2022-02-01_10.59.35-fml.txt](https://github.com/architectury/architectury-api/files/7979911/crash-2022-02-01_10.59.35-fml.txt)

**Comment by shedaniel** [comment] 2022-02-01 16:07
Duplicate of #135

**Closed as completed by shedaniel** 2022-02-01 16:07 UTC
Labels: duplicate, bug
